import { AssessmentBreakdown, PlayerAreaSummary } from '../components/AssessmentAreas'
import { BmiDisplay } from '../components/BmiDisplay'
import { useState } from 'react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { Activity, CalendarDays, TrendingUp, Users } from 'lucide-react'
import type { PortalData, Profile, Assessment, TrainingSession } from '../types'
import type { FormRequest } from '../components/Forms'
import { canCreateTeam, canEditTeam } from '../lib/access'
import { averageAssessment, categoryRating, rubric, formatRating, mean, metrics, overall, ratingLabel, ratingLabels } from '../lib/ratings'
import { deleteSession, errorMessage } from '../lib/data'
import { TrendChart } from '../components/TrendChart'
import { StatCard } from '../components/StatCard'
import { Modal } from '../components/Modal'
export type PageProps = { data: PortalData; profile: Profile; search: string; openForm: (request: FormRequest) => void; reload: () => Promise<void> }
const dateLabel = (date: string) => new Date(`${date}T00:00:00`).toLocaleDateString(undefined, { day:'numeric', month:'short', year:'numeric' })
const match = (text: string, search: string) => text.toLowerCase().includes(search.toLowerCase())
export function Unavailable() { return <section className="panel placeholder"><h1>Page unavailable</h1><p>This item does not exist or you do not have access.</p><Link to="/">Back to dashboard</Link></section> }
export function Rating({ value }: { value: number | null }) { return <span className={`rating ${value===null?'':value>=4?'good':value>=3?'mid':'low'}`} title={ratingLabel(value)}>{formatRating(value)}</span> }
export function RatingGuide() { return <div className="rating-guide">{ratingLabels.map((label,i)=><span key={label}><b>{i+1}</b> {label}</span>)}</div> }
function TeamFilter({ teams, value, onChange }: { teams: PortalData['teams']; value: string; onChange: (id:string)=>void }) { return <label className="filter-label">Team<select value={value} onChange={e=>onChange(e.target.value)}><option value="">All Teams</option>{teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label> }
function PlayerTable({ data, players = data.players }: { data: PortalData; players?: PortalData['players'] }) {
  return <div className="panel table-panel"><table><thead><tr><th>Player</th><th>Team</th><th>Position</th><th>Assessments</th><th>Overall (1–5)</th></tr></thead><tbody>{players.map(p=>{const list=data.assessments.filter(a=>a.player_id===p.id);return <tr key={p.id}><td><Link to={`/players/${p.id}`}>{p.full_name}</Link>{!p.active && <small> · Inactive</small>}</td><td>{data.teams.find(t=>t.id===p.team_id)?.name}</td><td>{p.position||'—'}</td><td>{list.length}</td><td><Rating value={overall(list)}/></td></tr>})}</tbody></table>{!players.length && <p className="empty">No players found.</p>}</div>
}
export function Dashboard({ data, profile, openForm }: PageProps) {
  const [trendTeam,setTrendTeam]=useState('')
  const upcoming=data.sessions.filter(s=>s.session_date>=new Date().toLocaleDateString('en-CA')).sort((a,b)=>a.session_date.localeCompare(b.session_date)).slice(0,4)
  return <><div className="welcome-row"><div><h1>Welcome back, {profile.full_name.split(' ')[0]}!</h1><p>Your teams, training sessions and player development.</p></div></div><div className="stats-grid">
    <StatCard to="/teams" icon={Users} value={data.teams.length} label="Teams" note="View your squads"/><StatCard to="/sessions" icon={CalendarDays} value={data.sessions.length} label="Training Sessions" note="Browse sessions by team"/><StatCard to="/players" icon={Activity} value={data.players.length} label="Players" note="View player profiles"/><StatCard to="/performance" icon={TrendingUp} value={formatRating(overall(data.assessments))} label="Avg. Performance" note="Five-point assessment scale"/>
  </div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>Your Teams</h2>{canCreateTeam(profile)&&<button className="small-primary" onClick={()=>openForm({kind:'team'})}>Add Team</button>}</div><div className="team-list">{data.teams.slice(0,4).map((t,i)=><Link to={`/teams/${t.id}`} className="team-row" key={t.id}><div className={`team-badge badge-${i%4}`}>{t.name.slice(0,2)}</div><div className="grow"><strong>{t.name}</strong><span>{data.players.filter(p=>p.team_id===t.id).length} players · {t.season||'Current season'}</span></div><span className="age-pill">{t.age_group||'Team'}</span></Link>)}{!data.teams.length&&<p className="empty">No teams assigned. Contact your administrator for access.</p>}</div></section>
    <section className="panel"><div className="panel-head"><h2>Upcoming Training Sessions</h2><Link to="/sessions">View all</Link></div><div className="session-list">{upcoming.map(s=><Link className="session-row" key={s.id} to={`/sessions/${s.id}`}><div className="date-box"><span>{s.session_date.slice(5)}</span></div><div><strong>{s.title}</strong><div>{data.teams.find(t=>t.id===s.team_id)?.name}</div><span>{s.duration_minutes??'—'} min · {s.focus||'Training session'}</span></div></Link>)}{!upcoming.length&&<p className="empty">No upcoming sessions.</p>}</div></section>
    <section><div className="panel-head"><h2>Player Performance</h2><Link to="/players">View all players</Link></div><PlayerTable data={data} players={data.players.slice(0,5)}/></section><section className="panel"><div className="panel-head"><h2>Performance Trends</h2><TeamFilter teams={data.teams} value={trendTeam} onChange={setTrendTeam}/></div><TrendChart assessments={data.assessments.filter(a=>!trendTeam||a.team_id===trendTeam)}/></section></div><RatingGuide/></>
}
export function TeamsPage(props: PageProps) {
  const { data,profile,search,openForm }=props
  return <section><div className="section-head"><div><h1>Teams</h1><p>Your authorized squads.</p></div>{canCreateTeam(profile)&&<button className="primary-btn" onClick={()=>openForm({kind:'team'})}>Add Team</button>}</div><div className="cards-grid">{data.teams.filter(t=>match(t.name,search)).map((t,i)=><Link className="entity-card" key={t.id} to={`/teams/${t.id}`}><div className={`entity-icon badge-${i%4}`}>{t.name.slice(0,2)}</div><h3>{t.name}</h3><p>{t.age_group||'Open'} · {t.season||'No season'}</p><div className="entity-stat">{data.players.filter(p=>p.team_id===t.id).length} players</div></Link>)}</div>{!data.teams.length&&<p className="empty">No teams assigned.</p>}</section>
}
export function TeamPage({data,profile,search,openForm}:PageProps) {
  const { id }=useParams();const team=data.teams.find(t=>t.id===id)
  if(!team)return <Unavailable/>
  return <section><Link to="/teams">← Teams</Link><div className="section-head"><div><h1>{team.name}</h1><p>{team.age_group||'Open'} · {team.season||'No season'}</p></div><div className="button-pair"><Link className="secondary-btn" to={`/sessions?team=${team.id}`}>Training sessions</Link>{canEditTeam(profile,team,data.memberships)&&<button className="primary-btn" onClick={()=>openForm({kind:'player',teamId:team.id})}>Add Player</button>}</div></div><PlayerTable data={data} players={data.players.filter(p=>p.team_id===id&&match(p.full_name,search))}/></section>
}
export function PlayersPage({ data,profile,search,openForm }:PageProps) {
  const [params,setParams]=useSearchParams(),teamId=params.get('team')||''
  if(teamId&&!data.teams.some(t=>t.id===teamId))return <Unavailable/>
  const editable=data.teams.some(t=>canEditTeam(profile,t,data.memberships))
  return <section><div className="section-head"><div><h1>Players</h1><p>Open a player to view their profile and assessment history.</p></div>{editable&&<div className="button-pair"><button className="secondary-btn" onClick={()=>openForm({kind:'player'})}>Add Player</button><button className="primary-btn" onClick={()=>openForm({kind:'assessment'})}>New Assessment</button></div>}</div><TeamFilter teams={data.teams} value={teamId} onChange={id=>setParams(id?{team:id}:{})}/><PlayerTable data={data} players={data.players.filter(p=>(!teamId||p.team_id===teamId)&&match(`${p.full_name} ${p.position??''}`,search))}/><RatingGuide/></section>
}
function AssessmentTable({ assessments, data }: { assessments:Assessment[]; data:PortalData }) { return <div className="panel table-panel"><table><thead><tr><th>Date</th><th>Session</th>{metrics.map(k=><th key={k}>{k}</th>)}<th>Overall</th><th>Comments</th><th>Assessment Areas</th></tr></thead><tbody>{assessments.map(a=><tr key={a.id}><td>{dateLabel(a.assessment_date)}</td><td>{a.session_id?<Link to={`/sessions/${a.session_id}`}>{data.sessions.find(s=>s.id===a.session_id)?.title??'Session'}</Link>:'No linked session'}</td>{metrics.map(k=><td key={k} title={ratingLabel(categoryRating(a,k))}>{formatRating(categoryRating(a,k))}</td>)}<td><Rating value={averageAssessment(a)}/></td><td className="multiline">{a.comments||'—'}</td><td>{a.area_ratings?<details><summary>View area ratings</summary><AssessmentBreakdown ratings={a.area_ratings}/></details>:'Category-only assessment'}</td></tr>)}</tbody></table>{!assessments.length&&<p className="empty">No assessments yet.</p>}</div> }
export function PlayerPage({data,profile,openForm}:PageProps) {
  const { id }=useParams(),p=data.players.find(p=>p.id===id)
  if(!p)return <Unavailable/>
  const team=data.teams.find(t=>t.id===p.team_id)!,list=data.assessments.filter(a=>a.player_id===p.id)
  const fields=[['Name',p.full_name],['Nick Name',p.nickname||'Not set'],['Mobile number',p.mobile_number||'Not set'],['Height',p.height_cm?`${p.height_cm} cm`:'Not set'],['Weight',p.weight_kg?`${p.weight_kg} kg`:'Not set'],['Team',team.name],['Status',p.active?'Active':'Inactive'],['Jersey number',p.jersey_number??'Not set'],['Position',p.position||'Not set'],['Date of birth',p.date_of_birth?dateLabel(p.date_of_birth):'Not set'],['Preferred foot',p.preferred_foot||'Not set'],['Notes',p.notes||'No notes'],['Linked account',p.linked_user_id?'Linked':'Not linked']]
  return <section><Link to="/players">← Players</Link><div className="section-head"><div><h1>{p.full_name}</h1><p>Player Profile · {team.name}</p></div>{canEditTeam(profile,team,data.memberships)&&<div className="button-pair"><button className="secondary-btn" onClick={()=>openForm({kind:'player',player:p})}>Edit Player</button><button className="primary-btn" onClick={()=>openForm({kind:'assessment',player:p})}>Review / Assess Player</button></div>}</div><dl className="profile-details panel">{fields.map(([label,value])=><div key={label}><dt>{label}</dt><dd className="multiline">{value}</dd></div>)}<div><dt>BMI</dt><dd><BmiDisplay heightCm={p.height_cm} weightKg={p.weight_kg} dateOfBirth={p.date_of_birth}/></dd></div></dl><div className="section-head"><h2>Performance · {list.length} assessments</h2><Rating value={overall(list)}/></div><div className="metric-grid">{metrics.map(k=><div className="entity-card" key={k}><h3 className="capitalize">{k}</h3><Rating value={mean(list.map(a=>categoryRating(a,k)))}/></div>)}</div><RatingGuide/><section className="panel"><h2 className="padded">Performance Trends</h2><TrendChart assessments={list}/></section><PlayerAreaSummary assessments={list}/><h2>Assessment History</h2><AssessmentTable data={data} assessments={list}/></section>
}
export function SessionsPage({data,profile,search,openForm}:PageProps) {
  const [params,setParams]=useSearchParams(),teamId=params.get('team')||''
  const [grouped,setGrouped]=useState(true)
  if(teamId&&!data.teams.some(t=>t.id===teamId))return <Unavailable/>
  const list=data.sessions.filter(s=>(!teamId||s.team_id===teamId)&&match(`${s.title} ${s.focus??''} ${data.teams.find(t=>t.id===s.team_id)?.name??''}`,search))
  function table(sessions:TrainingSession[]){return <div className="panel table-panel"><table><thead><tr><th>Date</th><th>Team</th><th>Session</th><th>Focus</th><th>Duration</th></tr></thead><tbody>{sessions.map(s=><tr key={s.id}><td>{dateLabel(s.session_date)}</td><td>{data.teams.find(t=>t.id===s.team_id)?.name}</td><td><Link to={`/sessions/${s.id}`}>{s.title}</Link></td><td>{s.focus||'—'}</td><td>{s.duration_minutes??'—'} min</td></tr>)}</tbody></table></div>}
  return <section><div className="section-head"><div><h1>Training Sessions</h1><p>Open a session to view details, edit or delete it.</p></div>{data.teams.some(t=>canEditTeam(profile,t,data.memberships))&&<button className="primary-btn" onClick={()=>openForm({kind:'session',teamId})}>New Session</button>}</div><div className="filters"><TeamFilter teams={data.teams} value={teamId} onChange={id=>setParams(id?{team:id}:{})}/><label><input type="checkbox" checked={grouped} onChange={e=>setGrouped(e.target.checked)}/> Group by team</label></div>{!list.length?<p className="empty">No sessions found.</p>:grouped?data.teams.filter(t=>list.some(s=>s.team_id===t.id)).map(t=><section key={t.id}><h2>{t.name}</h2>{table(list.filter(s=>s.team_id===t.id))}</section>):table(list)}</section>
}
export function SessionPage({data,profile,openForm,reload}:PageProps) {
  const { id }=useParams(),navigate=useNavigate(),session=data.sessions.find(s=>s.id===id)
  const [confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
  if(!session)return <Unavailable/>
  const team=data.teams.find(t=>t.id===session.team_id)!,linked=data.assessments.filter(a=>a.session_id===id)
  async function remove(){if(!session||busy)return;setBusy(true);setError('');try{await deleteSession(session.id);await reload();navigate('/sessions',{replace:true})}catch(err){setError(errorMessage(err));setBusy(false)}}
  return <section><Link to={`/sessions?team=${session.team_id}`}>← Training sessions</Link><div className="section-head"><div><h1>{session.title}</h1><p>{team.name} · {dateLabel(session.session_date)}</p></div>{canEditTeam(profile,team,data.memberships)&&<div className="button-pair"><button className="secondary-btn" onClick={()=>openForm({kind:'session',session})}>Edit Session</button><button className="danger-btn" onClick={()=>setConfirm(true)}>Delete Session</button></div>}</div><dl className="profile-details panel"><div><dt>Focus</dt><dd>{session.focus||'Not set'}</dd></div><div><dt>Duration</dt><dd>{session.duration_minutes??'Not set'} minutes</dd></div><div><dt>Notes</dt><dd className="multiline">{session.notes||'No notes'}</dd></div></dl><h2>Session Assessments</h2><div className="panel table-panel"><table><thead><tr><th>Player</th><th>Overall</th><th>Comments</th></tr></thead><tbody>{linked.map(a=><tr key={a.id}><td><Link to={`/players/${a.player_id}`}>{data.players.find(p=>p.id===a.player_id)?.full_name??'Player'}</Link></td><td><Rating value={averageAssessment(a)}/></td><td className="multiline">{a.comments||'—'}</td></tr>)}</tbody></table>{!linked.length&&<p className="empty">No linked assessments.</p>}</div>{confirm&&<Modal title="Delete training session?" onClose={()=>setConfirm(false)} busy={busy}><p>Delete “{session.title}” on {dateLabel(session.session_date)}? This cannot be undone. The {linked.length} linked assessments will be kept in player history without a session link.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="secondary-btn" disabled={busy} onClick={()=>setConfirm(false)}>Cancel</button><button className="danger-btn" disabled={busy} onClick={remove}>{busy?'Deleting…':'Confirm Delete'}</button></div></Modal>}</section>
}
export function ReportsPage({data}:PageProps) {
  const [teamId,setTeamId]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('')
  const invalid=!!from&&!!to&&from>to
  const list=data.assessments.filter(a=>(!teamId||a.team_id===teamId)&&(!from||a.assessment_date>=from)&&(!to||a.assessment_date<=to))
  const reportData={...data,assessments:list}
  function exportCsv(){
    const rows=[['Player','Team','Date',...metrics,'Overall (1–5)','Comments','Assessment type',...metrics.flatMap(k=>rubric[k].map(area=>`${k}: ${area.label}`))],...list.map(a=>[data.players.find(p=>p.id===a.player_id)?.full_name??'',data.teams.find(t=>t.id===a.team_id)?.name??'',a.assessment_date,...metrics.map(k=>categoryRating(a,k)?.toFixed(2)??''),averageAssessment(a)?.toFixed(2)??'',a.comments??'',a.area_ratings?'Detailed':'Category-only',...metrics.flatMap(k=>rubric[k].map(area=>a.area_ratings?.[k][area.id]??''))])]
    const csv=rows.map(row=>row.map(value=>{let text=String(value);if(/^[=+\-@\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"'}).join(',')).join('\r\n')
    const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='coachportal-assessments-1-to-5.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
  }
  return <section><div className="section-head"><div><h1>Reports</h1><p>Assessment averages and export on the 1–5 scale.</p></div><button className="primary-btn" disabled={invalid||!list.length} onClick={exportCsv}>Download CSV</button></div><div className="filters"><TeamFilter teams={data.teams} value={teamId} onChange={setTeamId}/><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{invalid?<p role="alert" className="form-error">End date must be on or after start date.</p>:<><p>{list.length} assessments · <Rating value={overall(list)}/></p><PlayerTable data={reportData} players={data.players.filter(p=>!teamId||p.team_id===teamId)}/><TrendChart assessments={list}/></>}<RatingGuide/></section>
}
